version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartordermanagement-web
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - smartorder_net

networks:
  smartorder_net:
    external: true
